cdn_provider: ''
_core:
  default_config_hash: 2bdTm0hxyupILZiXABj7eg2Hp9H8MdW_k7U9xmhoP4M
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://social-commerce.dev/themes/custom/bearded/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  bearded: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://logo_0.png'
  url: ''
  use_default: true
table_responsive: '-1'
table: ''
