toolbar_items:
  - devel.admin_settings_link
  - devel.cache_clear
  - devel.container_info.service
  - devel.execute_php
  - devel.menu_rebuild
  - devel.reinstall
  - devel.route_info
  - devel.run_cron
_core:
  default_config_hash: UcE4Y7pK7ppFQhLnQJfmgT6XjJxBn1LSJpIhvz2gDDI
