assets:
  - social-commerce.tar.gz
  - social-commerce.sql.gz
steps:
  - name : Composer install
    plugin: Script
    script: |
      set -e
      cd $SRC_DIR
      composer self-update
      composer install
  - name: Social commerce site setup
    plugin: Drupal
    installArgs: "--site-name='Social commerce' --account-name=admin --account-pass=UvyowwuAjQuiOrt5 --site-mail='taieb@angrycactus.biz' --account-mail='taieb@angrycactus.biz'"
    profileName: social_commerce
    runInstall: social_commerce
    database: social-commerce.sql.gz
    databaseGzipped: true
    clearCaches: false
  - name: Post script setup 
    plugin: Script
    script: |
      set -e
      cd $SRC_DIR/sites/default
      mv $ASSET_DIR/social-commerce.tar.gz .
      tar xfz social-commerce.tar.gz
      rm social-commerce.tar.gz
      drush cache-rebuild
