assets:
  - bearded.tar.gz
  - bearded.sql.gz
steps:
  - name : Composer install
    plugin: Script
    script: |
      set -e
      cd $SRC_DIR
      composer self-update
      composer install
  - name: Bearded site setup
    plugin: Drupal
    runInstall: social_commerce
    database: bearded.sql.gz
    databaseGzipped: true
    clearCaches: false
  - name: Post setup script
    plugin: Script
    script: |
      set -e
      cd $SRC_DIR/sites/default
      mv $ASSET_DIR/bearded.tar.gz .
      tar xfz bearded.tar.gz
      rm bearded.tar.gz
      drush upwd admin --password="cabiat705"
      drush cache-rebuild
