<?php

/**
 * @file
 * Pass variables to Twig template.
 */

/**
 * Implements hook_theme().
 */
function commerce_variation_add_to_cart_theme() {
  return array(
    'variation_add_to_cart_formatter' => array(
      'variables' =>
        array(
          'product_id' => NULL,
          'variation_id' => NULL,
          'show_price' => NULL,
          'price_number' => NULL,
          'price_format' => NULL,
          'show_currency' => NULL,
          'price_currency' => NULL,
          'show_quantity' => NULL,
          'attributes' => NULL,
          'destination' => NULL,
        ),
    ),
  );
}
