# Schema for the configuration files of the EntityBlock module.
field.widget.settings.entityblock_default:
  type: mapping
  label: 'EntityBlock format settings'
  mapping:
    view_modes:
      type: sequence
      label: 'Available view modes'
      sequence:
        - type: string
    force_enabled:
      type: boolean
      label: 'Force "Display as block"'
    force_title:
      type: boolean
      label: 'Force "Block title"'

field.field_settings.entityblock:
  type: mapping
  label: 'EntityBlock settings'
  mapping:
    enabled:
      type: boolean
      label: 'Block enabled'
    title:
      type: label
      label: 'Block title'
    view_mode:
      type: string
      label: 'View mode'
