commerce_order.commerce_order_type.*:
  type: commerce_config_entity_bundle
  label: 'Order type'
  mapping:
    workflow:
      type: string
      label: 'Workflow'
    refresh_mode:
      type: string
      label: 'Order refresh mode'
    refresh_frequency:
      type: integer
      label: 'Order refresh frequency'
    sendReceipt:
      type: boolean
      label: 'Email the customer a receipt when an order is placed'
    receiptBcc:
      type: string
      label: 'The receipt BCC email'

commerce_order.commerce_order_item_type.*:
  type: commerce_config_entity_bundle
  label: 'Order item type'
  mapping:
    purchasableEntityType:
      type: string
      label: 'Purchasable entity type'
    orderType:
      type: string
      label: 'Order type'
