name: Commerce Configuration
description: Contains commerce module settings.
package: Custom

type: module
core: 8.x

dependencies:
  - commerce:commerce
  - commerce:commerce_cart
  - commerce:commerce_order
  - commerce:commerce_price
  - commerce:commerce_product
  - commerce:commerce_store
